displayName=Notable Players
author=pairofcrocs
description=Highlights notable players (content creators, Jagex Mods, unique accounts) and your own custom list
tags=highlight,players,content creators,streamers,mods,unique
plugins=com.notableplayers.NotablePlayersPlugin
version=
build=standard
